# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:/Software_dev/Python/silicon_app/designer/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_uvw = QtWidgets.QLabel(self.centralwidget)
        self.label_uvw.setObjectName("label_uvw")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_uvw)
        self.uvw = QtWidgets.QLineEdit(self.centralwidget)
        self.uvw.setObjectName("uvw")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.uvw)
        self.label_hkl = QtWidgets.QLabel(self.centralwidget)
        self.label_hkl.setObjectName("label_hkl")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_hkl)
        self.hkl = QtWidgets.QLineEdit(self.centralwidget)
        self.hkl.setObjectName("hkl")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.hkl)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label)
        self.dSB_alpha = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dSB_alpha.setEnabled(True)
        self.dSB_alpha.setReadOnly(True)
        self.dSB_alpha.setObjectName("dSB_alpha")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.dSB_alpha)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.dSB_gamma = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dSB_gamma.setEnabled(True)
        self.dSB_gamma.setReadOnly(True)
        self.dSB_gamma.setObjectName("dSB_gamma")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.dSB_gamma)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setMaximum(360)
        self.horizontalSlider.setSingleStep(45)
        self.horizontalSlider.setPageStep(45)
        self.horizontalSlider.setProperty("value", 180)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider.setTickInterval(45)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.SpanningRole, self.horizontalSlider)
        self.pB_compute = QtWidgets.QPushButton(self.centralwidget)
        self.pB_compute.setObjectName("pB_compute")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.pB_compute)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(15, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setMinimumSize(QtCore.QSize(20, 0))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.line_2)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setMinimumSize(QtCore.QSize(10, 0))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.SpanningRole, self.line_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_6)
        self.dSB_beta = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dSB_beta.setEnabled(True)
        self.dSB_beta.setReadOnly(True)
        self.dSB_beta.setObjectName("dSB_beta")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.dSB_beta)
        self.rB_deg = QtWidgets.QRadioButton(self.centralwidget)
        self.rB_deg.setObjectName("rB_deg")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.rB_deg)
        self.rB_rad = QtWidgets.QRadioButton(self.centralwidget)
        self.rB_rad.setChecked(True)
        self.rB_rad.setObjectName("rB_rad")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.rB_rad)
        self.horizontalLayout.addLayout(self.formLayout)
        self.plotLayout = QtWidgets.QVBoxLayout()
        self.plotLayout.setObjectName("plotLayout")
        self.horizontalLayout.addLayout(self.plotLayout)
        self.horizontalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.menuMain.addAction(self.action_exit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_uvw.setText(_translate("MainWindow", "uvw"))
        self.uvw.setText(_translate("MainWindow", "1,1,0"))
        self.label_hkl.setText(_translate("MainWindow", "hkl"))
        self.hkl.setText(_translate("MainWindow", "0,0,1"))
        self.label.setText(_translate("MainWindow", "Alpha"))
        self.label_2.setText(_translate("MainWindow", "Beta"))
        self.label_3.setText(_translate("MainWindow", "Gamma"))
        self.pB_compute.setText(_translate("MainWindow", "compute"))
        self.label_4.setText(_translate("MainWindow", "Eulerian angles"))
        self.label_5.setText(_translate("MainWindow", "Plot axis Z"))
        self.label_6.setText(_translate("MainWindow", "Plot axis X"))
        self.rB_deg.setText(_translate("MainWindow", "deg"))
        self.rB_rad.setText(_translate("MainWindow", "rad"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.action_exit.setText(_translate("MainWindow", "Exit"))
        self.action_exit.setShortcut(_translate("MainWindow", "Ctrl+Q"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
